http:
    addr: ":8080"
    username: admin
    password: cheese
    chartPath: "charts"

storage:
    enabled: false
    bucket_url: "s3://bucketrepo?endpoint=https://minio.minio-opeartor.svc.cluster.local&s3ForcePathStyle=true&region=us-east-1"

cache:
    base_dir: "/tmp/bucketrepo"

repositories:
    - url: "https://repo1.maven.org/maven2"
    - url: "http://uk.maven.org/maven2/"
